apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: prestashoptp
type: Opaque
data:
  prestashop_database_name: cHJlc3Rhc2hvcA== #prestashop
  prestashop_database_user: VGhvbWFz #Thomas
  prestashop_database_password: cGFzc3ByZXN0YQ== #passpresta
  mariadb_root_password: cGFzc21hcmlh #passmaria

